name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Files Using Appleboy SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          source: "." 
          target: "/home/${{ secrets.AZURE_USERNAME }}/app"

      - name: Deploy Application on Azure VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.AZURE_USERNAME }}/app

            # Build and Run Docker Container
            docker build -t fastapi-app .
            docker stop fastapi-app || true
            docker rm -f fastapi-app || true
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            # Validate and Restart Nginx
            sudo nginx -t && sudo systemctl restart nginx
