name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Copy Files to Azure VM
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          scp -i private_key -o StrictHostKeyChecking=no \
              -r . $AZURE_USERNAME@$AZURE_HOST:/home/$AZURE_USERNAME/app

      - name: Deploy Application on Azure VM
        env:
          AZURE_HOST: ${{ secrets.AZURE_HOST }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_HOST << 'EOF'
            cd /home/$AZURE_USERNAME/app

            # Build and Run Docker Container
            docker build -t fastapi-app .
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
