name: Continous Integration
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repos
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv .myvenv
          source .myvenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source .myvenv/bin/activate
          pytest